# Generated by Django 6.0 on 2025-12-13 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='staff',
            field=models.OneToOneField(limit_choices_to={'role__in': ['STAFF', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
